/**
 * Token pipeline — single source of truth.
 *
 * Reads DTCG-format JSON from style-dictionary/tokens/*.json and emits:
 *   1. src/styles/tokens.generated.css  — CSS :root custom-property block
 *   2. src/styles/tokens.generated.ts   — typed JS mirror (TOKENS export)
 *
 * Run: ./node_modules/.bin/tsx scripts/build-tokens.ts
 *
 * Output is deterministic (tokens sorted alphabetically by name), so running
 * twice produces byte-identical files.
 */

import StyleDictionary from 'style-dictionary'
import type { TransformedToken } from 'style-dictionary/types'
import { fileURLToPath } from 'url'
import path from 'path'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Kebab-case → camelCase */
function toCamel(s: string): string {
  return s.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())
}

/** Tokens that are only useful in CSS and should not appear in TOKENS export. */
const TS_SKIP = new Set(['e1', 'e2'])

/**
 * Token types to include in the TOKENS export.
 * Dimensions (spacing, radius, breakpoints), font families, and number (fs)
 * are CSS-only; JS/canvas layers don't need them.
 */
const TS_TYPES = new Set(['color', 'cubicBezier', 'duration', 'shadow'])

function shouldExportToTs(t: TransformedToken): boolean {
  return TS_TYPES.has((t.$type as string) ?? '') && !TS_SKIP.has(t.name)
}

/**
 * Render a token's value for the TypeScript export.
 *
 * - color / shadow / fontFamily → string literal
 * - duration → number in milliseconds  (callers divide by 1000 for seconds)
 * - cubicBezier → typed 4-tuple — uses original.$value (array) not the
 *   CSS-transformed string that the 'css' transformGroup produces
 * - number → plain number
 */
function toTsValue(t: TransformedToken): string {
  const type = (t.$type as string) ?? ''
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const orig = (t as any).original?.$value ?? t.$value

  if (type === 'cubicBezier') {
    const arr = orig as number[]
    return `[${arr.join(', ')}] as [number, number, number, number]`
  }
  if (type === 'duration') {
    // "$value" after css transform is still the string "120ms"; parse to number
    const raw = String(t.$value ?? orig)
    const ms = parseInt(raw, 10)
    return String(ms)
  }
  if (type === 'number') {
    return String(orig)
  }
  // color, shadow, fontFamily → quoted string
  return JSON.stringify(String(t.$value ?? orig))
}

// ---------------------------------------------------------------------------
// CSS format: :root { --name: value; } block, tokens sorted by name
// ---------------------------------------------------------------------------

const CSS_FORMAT_NAME = 'custom/css-root'
const TS_FORMAT_NAME = 'custom/ts-tokens'

const CSS_HEADER = [
  '/* DO NOT EDIT — generated by scripts/build-tokens.ts.',
  '   Run: ./node_modules/.bin/tsx scripts/build-tokens.ts */',
].join('\n')

const TS_HEADER = [
  '// DO NOT EDIT — generated by scripts/build-tokens.ts.',
  '// Run: ./node_modules/.bin/tsx scripts/build-tokens.ts',
  '//',
  '// TOKENS reference:',
  '//   color / shadow values : CSS strings (hex, rgba, box-shadow)',
  '//   duration values       : milliseconds — divide by 1000 for Motion seconds',
  '//   cubicBezier values    : [p1x, p1y, p2x, p2y] tuples',
].join('\n')

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

const sd = new StyleDictionary({
  source: [`${ROOT}/style-dictionary/tokens/*.json`],
  platforms: {
    css: {
      transformGroup: 'css',
      files: [
        {
          destination: `${ROOT}/src/styles/tokens.generated.css`,
          format: CSS_FORMAT_NAME,
        },
      ],
    },
    ts: {
      // Use 'css' transformGroup so names are produced via name/kebab; values
      // that need special TS treatment (cubicBezier, duration) are read from
      // original.$value in the formatter.
      transformGroup: 'css',
      files: [
        {
          destination: `${ROOT}/src/styles/tokens.generated.ts`,
          format: TS_FORMAT_NAME,
        },
      ],
    },
  },
})

sd.registerFormat({
  name: CSS_FORMAT_NAME,
  format: async ({ dictionary }) => {
    const sorted = [...dictionary.allTokens].sort((a, b) =>
      a.name.localeCompare(b.name),
    )
    const lines = sorted.map((t) => `  --${t.name}: ${String(t.$value)};`)
    return [CSS_HEADER, ':root {', ...lines, '}', ''].join('\n')
  },
})

sd.registerFormat({
  name: TS_FORMAT_NAME,
  format: async ({ dictionary }) => {
    const sorted = [...dictionary.allTokens]
      .filter(shouldExportToTs)
      .sort((a, b) => a.name.localeCompare(b.name))

    const entries = sorted.map((t) => {
      const key = toCamel(t.name)
      const val = toTsValue(t)
      return `  ${key}: ${val},`
    })

    return [
      TS_HEADER,
      '',
      'export const TOKENS = {',
      ...entries,
      '} as const',
      '',
    ].join('\n')
  },
})

await sd.buildAllPlatforms()
console.log('✓ tokens.generated.css and tokens.generated.ts written')
